FORMAT: 1A

# wuiguardians
WUIGuardians API is REST api, based on OAuth2 authorization protocol to provide access to the guardians resources.

# Group Wuis
Wuis related resources of the **Wuis API**

## Wuis Collection [/wuis]
### List all Wuis [GET]
+ Response 200 (application/json)

[{
  "id": 1, "type": "crash"
}, {
  "id": 2, "type": "key"
}]

